jobs:
  - job: win32
    timeoutInMinutes: 90
    strategy:
      matrix:
        vs2017-x86-win2016:
          vmImage: vs2017-win2016
          VS_VER: "15"
          PY_VER: "3.7"
          PLATFORM: "x86"
    pool:
      vmImage: $(vmImage)
    variables:
      DOWNLOAD_DIR: $(System.Workfolder)\_download_cache
      MSYS2_ROOT: $(System.Workfolder)\msys64
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(PY_VER)'
          architecture: '$(PLATFORM)'
      - task: CacheBeta@0
        inputs:
          key: download
          path: $(DOWNLOAD_DIR)
        displayName: Download cache
      - script: |
          choco config set cacheLocation %DOWNLOAD_DIR%
          choco install msys2 --params="/InstallDir:%MSYS2_ROOT% /NoPath"
        displayName: Install MSYS2
      - script: |
          python.exe build.py build --msys-dir=%MSYS2_ROOT% --archives-download-dir=%DOWNLOAD_DIR% --platform=%PLATFORM% --vs-ver=%VS_VER% -k --enable-gi --py-wheel --py-egg --python-ver %PY_VER% enchant gtk gtk3-full pycairo pygobject lz4
